import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Provider from "./(Provider)/NextUiProvider";

const inter=Inter({
  subsets: ["latin"],
  variable:"--font-inter"
})
const montserrat= Montserrat({subsets:['latin'],variable:'--font-montserrat'})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} antialiased`}
      >
        <Provider>{children}</Provider>
        
      </body>
    </html>
  );
}
